// File generated by Generate_Lang.bat
#ifndef _CURLANG_H
#define _CURLANG_H
/******************************************************************************
** File name    :        Cur_Language_Define.h
** Project      :        PV21
** File Type    :        Header
** Description	:        This file contains the definition of the current  
**                       language to build.
**                       The file will be replaced by a bat-file generated file
**                       when a full release is done.
**
** Revision History:
** Date         Engineer    ECP     Changes
** ----------------------------------------------------------------------------
** 2006-08-02   *   ErAn   *  ---  * 	File Created
** ----------------------------------------------------------------------------
**
******************************************************************************/

#define CURRENT_LANGUAGE LANGUAGE_CN 

#endif //_CURLANG_H
